import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import InfoBar from "@/components/InfoBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <InfoBar />
        <div className="flex justify-center">
          <div className="w-[1000px]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
